// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: pdfview.flex

import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class PdfView implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int BRACE_CONTENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\7\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u1f00\1\u2400\1\u2500\2\u1f00\31\u0100\1\u2600\121\u0100\1\u2700"+
    "\4\u0100\1\u2800\1\u0100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00"+
    "\1\u2e00\53\u0100\1\u2f00\10\u3000\31\u1f00\1\u0100\1\u3100\1\u3200"+
    "\1\u0100\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u3a00\1\u3b00\1\u0100\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u4100\1\u4200\1\u1f00\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u1f00"+
    "\1\u4f00\1\u5000\1\u5100\1\u1f00\3\u0100\1\u5200\1\u5300\1\u5400"+
    "\12\u1f00\4\u0100\1\u5500\17\u1f00\2\u0100\1\u5600\41\u1f00\2\u0100"+
    "\1\u5700\1\u5800\2\u1f00\1\u5900\1\u5a00\27\u0100\1\u5b00\2\u0100"+
    "\1\u5c00\45\u1f00\1\u0100\1\u5d00\1\u5e00\11\u1f00\1\u5f00\24\u1f00"+
    "\1\u6000\1\u6100\1\u1f00\1\u6200\1\u6300\1\u6400\1\u6500\2\u1f00"+
    "\1\u6600\5\u1f00\1\u6700\1\u6800\1\u6900\5\u1f00\1\u6a00\1\u6b00"+
    "\4\u1f00\1\u6c00\2\u1f00\1\u6d00\16\u1f00\246\u0100\1\u6e00\20\u0100"+
    "\1\u6f00\1\u7000\25\u0100\1\u7100\34\u0100\1\u7200\14\u1f00\2\u0100"+
    "\1\u7300\u0b06\u1f00\1\u2700\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\14\0\1\7\2\0\1\10\1\11\1\12\1\10\1\13"+
    "\5\10\7\0\1\14\1\15\1\16\1\17\1\20\2\10"+
    "\1\21\1\22\2\10\1\23\1\10\1\24\1\10\1\25"+
    "\3\10\1\26\1\27\5\10\4\0\1\10\1\0\32\10"+
    "\1\30\1\0\1\31\7\0\1\3\44\0\1\10\12\0"+
    "\1\10\4\0\1\10\5\0\27\10\1\0\37\10\1\0"+
    "\u01ca\10\4\0\14\10\16\0\5\10\7\0\1\10\1\0"+
    "\1\10\21\0\165\10\1\0\2\10\2\0\4\10\1\0"+
    "\1\10\6\0\1\10\1\0\3\10\1\0\1\10\1\0"+
    "\24\10\1\0\123\10\1\0\213\10\1\0\255\10\1\0"+
    "\46\10\2\0\1\10\6\0\51\10\10\0\55\10\1\0"+
    "\1\10\1\0\2\10\1\0\2\10\1\0\1\10\10\0"+
    "\33\10\4\0\4\10\35\0\13\10\5\0\112\10\4\0"+
    "\146\10\1\0\10\10\2\0\12\10\1\0\23\10\2\0"+
    "\1\10\20\0\73\10\2\0\145\10\16\0\66\10\4\0"+
    "\1\10\2\0\1\10\2\0\56\10\22\0\34\10\4\0"+
    "\13\10\65\0\25\10\1\0\10\10\25\0\17\10\1\0"+
    "\201\10\2\0\12\10\1\0\23\10\1\0\10\10\2\0"+
    "\2\10\2\0\26\10\1\0\7\10\1\0\1\10\3\0"+
    "\4\10\2\0\11\10\2\0\2\10\2\0\4\10\10\0"+
    "\1\10\4\0\2\10\1\0\5\10\2\0\14\10\12\0"+
    "\1\10\1\0\1\10\2\0\3\10\1\0\6\10\4\0"+
    "\2\10\2\0\26\10\1\0\7\10\1\0\2\10\1\0"+
    "\2\10\1\0\2\10\2\0\1\10\1\0\5\10\4\0"+
    "\2\10\2\0\3\10\3\0\1\10\7\0\4\10\1\0"+
    "\1\10\7\0\20\10\13\0\3\10\1\0\11\10\1\0"+
    "\3\10\1\0\26\10\1\0\7\10\1\0\2\10\1\0"+
    "\5\10\2\0\12\10\1\0\3\10\1\0\3\10\2\0"+
    "\1\10\17\0\4\10\2\0\12\10\11\0\7\10\1\0"+
    "\3\10\1\0\10\10\2\0\2\10\2\0\26\10\1\0"+
    "\7\10\1\0\2\10\1\0\5\10\2\0\11\10\2\0"+
    "\2\10\2\0\3\10\10\0\2\10\4\0\2\10\1\0"+
    "\5\10\2\0\12\10\1\0\1\10\20\0\2\10\1\0"+
    "\6\10\3\0\3\10\1\0\4\10\3\0\2\10\1\0"+
    "\1\10\1\0\2\10\3\0\2\10\3\0\3\10\3\0"+
    "\14\10\4\0\5\10\3\0\3\10\1\0\4\10\2\0"+
    "\1\10\6\0\1\10\16\0\12\10\20\0\15\10\1\0"+
    "\3\10\1\0\27\10\1\0\20\10\3\0\10\10\1\0"+
    "\3\10\1\0\4\10\7\0\2\10\1\0\3\10\5\0"+
    "\4\10\2\0\12\10\20\0\4\10\1\0\10\10\1\0"+
    "\3\10\1\0\27\10\1\0\12\10\1\0\5\10\2\0"+
    "\11\10\1\0\3\10\1\0\4\10\7\0\2\10\7\0"+
    "\1\10\1\0\4\10\2\0\12\10\1\0\2\10\15\0"+
    "\4\10\1\0\10\10\1\0\3\10\1\0\63\10\1\0"+
    "\3\10\1\0\5\10\5\0\4\10\7\0\5\10\2\0"+
    "\12\10\12\0\6\10\2\0\2\10\1\0\22\10\3\0"+
    "\30\10\1\0\11\10\1\0\1\10\2\0\7\10\3\0"+
    "\1\10\4\0\6\10\1\0\1\10\1\0\10\10\6\0"+
    "\12\10\2\0\2\10\15\0\72\10\5\0\17\10\1\0"+
    "\12\10\47\0\2\10\1\0\1\10\1\0\5\10\1\0"+
    "\30\10\1\0\1\10\1\0\27\10\2\0\5\10\1\0"+
    "\1\10\1\0\6\10\2\0\12\10\2\0\4\10\40\0"+
    "\1\10\27\0\2\10\6\0\12\10\13\0\1\10\1\0"+
    "\1\10\1\0\1\10\4\0\12\10\1\0\44\10\4\0"+
    "\24\10\1\0\22\10\1\0\44\10\11\0\1\10\71\0"+
    "\112\10\6\0\116\10\2\0\46\10\1\0\1\10\5\0"+
    "\1\10\2\0\53\10\1\0\115\10\1\0\4\10\2\0"+
    "\7\10\1\0\1\10\1\0\4\10\2\0\51\10\1\0"+
    "\4\10\2\0\41\10\1\0\4\10\2\0\7\10\1\0"+
    "\1\10\1\0\4\10\2\0\17\10\1\0\71\10\1\0"+
    "\4\10\2\0\103\10\2\0\3\10\40\0\20\10\20\0"+
    "\126\10\2\0\6\10\3\0\u016c\10\2\0\21\10\1\0"+
    "\32\10\5\0\113\10\3\0\13\10\7\0\15\10\1\0"+
    "\7\10\13\0\25\10\13\0\24\10\14\0\15\10\1\0"+
    "\3\10\1\0\2\10\14\0\124\10\3\0\1\10\4\0"+
    "\2\10\2\0\12\10\41\0\3\10\2\0\12\10\6\0"+
    "\131\10\7\0\53\10\5\0\106\10\12\0\37\10\1\0"+
    "\14\10\4\0\14\10\12\0\50\10\2\0\5\10\13\0"+
    "\54\10\4\0\32\10\6\0\12\10\46\0\34\10\4\0"+
    "\77\10\1\0\35\10\2\0\13\10\6\0\12\10\15\0"+
    "\1\10\10\0\17\10\101\0\114\10\4\0\12\10\21\0"+
    "\11\10\14\0\164\10\14\0\70\10\10\0\12\10\3\0"+
    "\61\10\2\0\11\10\7\0\53\10\2\0\3\10\20\0"+
    "\3\10\1\0\47\10\5\0\372\10\1\0\33\10\2\0"+
    "\6\10\2\0\46\10\2\0\6\10\2\0\10\10\1\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\0\37\10\2\0"+
    "\65\10\1\0\7\10\1\0\1\10\3\0\3\10\1\0"+
    "\7\10\3\0\4\10\2\0\6\10\4\0\15\10\5\0"+
    "\3\10\1\0\7\10\53\0\2\3\25\0\2\10\23\0"+
    "\1\10\34\0\1\10\15\0\1\10\20\0\15\10\63\0"+
    "\41\10\21\0\1\10\4\0\1\10\2\0\12\10\1\0"+
    "\1\10\3\0\5\10\6\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\0\4\10\1\0\13\10\2\0\4\10\5\0"+
    "\5\10\4\0\1\10\21\0\51\10\u022d\0\64\10\26\0"+
    "\57\10\1\0\57\10\1\0\205\10\6\0\11\10\14\0"+
    "\46\10\1\0\1\10\5\0\1\10\2\0\70\10\7\0"+
    "\1\10\17\0\30\10\11\0\7\10\1\0\7\10\1\0"+
    "\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0"+
    "\7\10\1\0\7\10\1\0\40\10\57\0\1\10\325\0"+
    "\3\10\31\0\17\10\1\0\5\10\2\0\5\10\4\0"+
    "\126\10\2\0\2\10\2\0\3\10\1\0\132\10\1\0"+
    "\4\10\5\0\53\10\1\0\136\10\21\0\33\10\65\0"+
    "\306\10\112\0\360\10\20\0\215\10\103\0\56\10\2\0"+
    "\15\10\3\0\34\10\24\0\63\10\1\0\12\10\1\0"+
    "\163\10\45\0\11\10\2\0\147\10\2\0\65\10\2\0"+
    "\5\10\60\0\61\10\30\0\64\10\14\0\106\10\12\0"+
    "\12\10\6\0\30\10\3\0\1\10\1\0\61\10\2\0"+
    "\44\10\14\0\35\10\3\0\101\10\16\0\13\10\6\0"+
    "\37\10\1\0\67\10\11\0\16\10\2\0\12\10\6\0"+
    "\27\10\3\0\111\10\30\0\3\10\2\0\20\10\2\0"+
    "\5\10\12\0\6\10\2\0\6\10\2\0\6\10\11\0"+
    "\7\10\1\0\7\10\1\0\53\10\1\0\14\10\10\0"+
    "\173\10\1\0\2\10\2\0\12\10\6\0\244\10\14\0"+
    "\27\10\4\0\61\10\4\0\u0100\3\156\10\2\0\152\10"+
    "\46\0\7\10\14\0\5\10\5\0\14\10\1\0\15\10"+
    "\1\0\5\10\1\0\1\10\1\0\2\10\1\0\2\10"+
    "\1\0\154\10\41\0\153\10\22\0\100\10\2\0\66\10"+
    "\50\0\14\10\4\0\20\10\20\0\20\10\3\0\2\10"+
    "\30\0\3\10\40\0\5\10\1\0\207\10\23\0\12\10"+
    "\7\0\32\10\4\0\1\10\1\0\32\10\13\0\131\10"+
    "\3\0\6\10\2\0\6\10\2\0\6\10\2\0\3\10"+
    "\43\0\14\10\1\0\32\10\1\0\23\10\1\0\2\10"+
    "\1\0\17\10\2\0\16\10\42\0\173\10\105\0\65\10"+
    "\210\0\1\10\202\0\35\10\3\0\61\10\17\0\1\10"+
    "\37\0\40\10\15\0\36\10\5\0\53\10\5\0\36\10"+
    "\2\0\44\10\4\0\10\10\1\0\5\10\52\0\236\10"+
    "\2\0\12\10\6\0\44\10\4\0\44\10\4\0\50\10"+
    "\10\0\64\10\234\0\67\10\11\0\26\10\12\0\10\10"+
    "\230\0\6\10\2\0\1\10\1\0\54\10\1\0\2\10"+
    "\3\0\1\10\2\0\27\10\12\0\27\10\11\0\37\10"+
    "\101\0\23\10\1\0\2\10\12\0\26\10\12\0\32\10"+
    "\106\0\70\10\6\0\2\10\100\0\4\10\1\0\2\10"+
    "\5\0\10\10\1\0\3\10\1\0\35\10\2\0\3\10"+
    "\4\0\1\10\40\0\35\10\3\0\35\10\43\0\10\10"+
    "\1\0\36\10\31\0\66\10\12\0\26\10\12\0\23\10"+
    "\15\0\22\10\156\0\111\10\67\0\63\10\15\0\63\10"+
    "\15\0\50\10\10\0\12\10\306\0\35\10\12\0\1\10"+
    "\10\0\41\10\217\0\27\10\11\0\107\10\37\0\12\10"+
    "\17\0\74\10\25\0\31\10\7\0\12\10\6\0\65\10"+
    "\1\0\12\10\4\0\3\10\11\0\44\10\2\0\1\10"+
    "\11\0\105\10\4\0\4\10\3\0\13\10\1\0\1\10"+
    "\43\0\22\10\1\0\45\10\6\0\1\10\101\0\7\10"+
    "\1\0\1\10\1\0\4\10\1\0\17\10\1\0\12\10"+
    "\7\0\73\10\5\0\12\10\6\0\4\10\1\0\10\10"+
    "\2\0\2\10\2\0\26\10\1\0\7\10\1\0\2\10"+
    "\1\0\5\10\1\0\12\10\2\0\2\10\2\0\3\10"+
    "\2\0\1\10\6\0\1\10\5\0\7\10\2\0\7\10"+
    "\3\0\5\10\213\0\113\10\5\0\12\10\4\0\2\10"+
    "\40\0\106\10\1\0\1\10\10\0\12\10\246\0\66\10"+
    "\2\0\11\10\27\0\6\10\42\0\101\10\3\0\1\10"+
    "\13\0\12\10\46\0\71\10\7\0\12\10\66\0\33\10"+
    "\2\0\17\10\4\0\12\10\306\0\73\10\145\0\112\10"+
    "\25\0\1\10\240\0\10\10\2\0\56\10\2\0\10\10"+
    "\1\0\2\10\33\0\77\10\10\0\1\10\10\0\112\10"+
    "\3\0\1\10\42\0\71\10\7\0\11\10\1\0\55\10"+
    "\1\0\11\10\17\0\12\10\30\0\36\10\2\0\26\10"+
    "\1\0\16\10\111\0\7\10\1\0\2\10\1\0\54\10"+
    "\3\0\1\10\1\0\2\10\1\0\11\10\10\0\12\10"+
    "\6\0\6\10\1\0\2\10\1\0\45\10\1\0\2\10"+
    "\1\0\6\10\7\0\12\10\u0136\0\27\10\11\0\232\10"+
    "\146\0\157\10\21\0\304\10\274\0\57\10\321\0\107\10"+
    "\271\0\71\10\7\0\37\10\1\0\12\10\146\0\36\10"+
    "\2\0\5\10\13\0\67\10\11\0\4\10\14\0\12\10"+
    "\11\0\25\10\5\0\23\10\260\0\100\10\200\0\113\10"+
    "\4\0\71\10\7\0\21\10\100\0\2\10\1\0\1\10"+
    "\34\0\370\10\10\0\363\10\15\0\37\10\61\0\3\10"+
    "\21\0\4\10\10\0\u018c\10\4\0\153\10\5\0\15\10"+
    "\3\0\11\10\7\0\12\10\3\0\2\10\306\0\5\10"+
    "\3\0\6\10\10\0\10\10\2\0\7\10\36\0\4\10"+
    "\224\0\3\10\273\0\125\10\1\0\107\10\1\0\2\10"+
    "\2\0\1\10\2\0\2\10\2\0\4\10\1\0\14\10"+
    "\1\0\1\10\1\0\7\10\1\0\101\10\1\0\4\10"+
    "\2\0\10\10\1\0\7\10\1\0\34\10\1\0\4\10"+
    "\1\0\5\10\1\0\1\10\3\0\7\10\1\0\u0154\10"+
    "\2\0\31\10\1\0\31\10\1\0\37\10\1\0\31\10"+
    "\1\0\37\10\1\0\31\10\1\0\37\10\1\0\31\10"+
    "\1\0\37\10\1\0\31\10\1\0\10\10\2\0\151\10"+
    "\4\0\62\10\10\0\1\10\16\0\1\10\26\0\5\10"+
    "\1\0\17\10\120\0\7\10\1\0\21\10\2\0\7\10"+
    "\1\0\2\10\1\0\5\10\325\0\55\10\3\0\16\10"+
    "\2\0\12\10\4\0\1\10\u0171\0\72\10\6\0\305\10"+
    "\13\0\7\10\51\0\114\10\4\0\12\10\246\0\4\10"+
    "\1\0\33\10\1\0\2\10\1\0\1\10\2\0\1\10"+
    "\1\0\12\10\1\0\4\10\1\0\1\10\1\0\1\10"+
    "\6\0\1\10\4\0\1\10\1\0\1\10\1\0\1\10"+
    "\1\0\3\10\1\0\2\10\1\0\1\10\2\0\1\10"+
    "\1\0\1\10\1\0\1\10\1\0\1\10\1\0\1\10"+
    "\1\0\2\10\1\0\1\10\2\0\4\10\1\0\7\10"+
    "\1\0\4\10\1\0\4\10\1\0\1\10\1\0\12\10"+
    "\1\0\21\10\5\0\3\10\1\0\5\10\1\0\21\10"+
    "\164\0\32\10\6\0\32\10\6\0\32\10\166\0\327\10"+
    "\51\0\65\10\13\0\336\10\2\0\u0182\10\16\0\u0131\10"+
    "\37\0\36\10\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29696];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\5\1\1\3\2\1\1\4\1\1"+
    "\1\5\1\6\1\7\1\10\1\0\1\11\1\12\1\13"+
    "\2\0\1\14\1\15\1\16\1\2\1\17\4\0\1\20"+
    "\1\21\1\22\1\23\1\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[39];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\32\0\64\0\64\0\116\0\150\0\202\0\234"+
    "\0\266\0\320\0\64\0\352\0\u0104\0\64\0\u011e\0\64"+
    "\0\u0138\0\64\0\64\0\u0152\0\64\0\u016c\0\u0186\0\u01a0"+
    "\0\u01ba\0\64\0\u01d4\0\64\0\u0152\0\64\0\u01ee\0\u0208"+
    "\0\u0222\0\u023c\0\64\0\u0208\0\64\0\64\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[39];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\4\1\5\1\4\1\6\4\3"+
    "\1\7\1\10\1\11\1\12\1\3\1\13\1\14\1\3"+
    "\1\15\1\16\1\17\1\3\1\20\1\3\30\21\1\22"+
    "\1\23\34\0\1\4\36\0\1\24\37\0\1\25\11\0"+
    "\1\26\27\0\1\27\21\0\1\30\30\0\1\31\42\0"+
    "\1\32\25\0\1\33\33\0\1\34\6\0\30\21\2\0"+
    "\2\35\4\0\24\35\22\0\1\36\15\0\1\37\31\0"+
    "\1\40\51\0\1\41\11\0\1\42\36\0\1\43\26\0"+
    "\20\44\22\0\1\45\22\0\1\46\1\47\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[598];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\6\1\1\11\2\1\1\11\1\1\1\11"+
    "\1\1\2\11\1\0\1\11\2\1\2\0\1\11\1\1"+
    "\1\11\1\1\1\11\4\0\1\11\1\1\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[39];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }

    private StringBuilder contentBuffer = new StringBuilder();
    private int braceDepth = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  PdfView(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Invalid character at line " + yyline + " column " + yycolumn + ": '" + yytext() + "'");
            }
            // fall through
          case 21: break;
          case 2:
            { /* Ignore */
            }
            // fall through
          case 22: break;
          case 3:
            { return symbol(sym.H);
            }
            // fall through
          case 23: break;
          case 4:
            { return symbol(sym.P);
            }
            // fall through
          case 24: break;
          case 5:
            { contentBuffer.setLength(0);
        braceDepth = 1;
        yybegin(BRACE_CONTENT);
            }
            // fall through
          case 25: break;
          case 6:
            { // String matched = yytext();
            // System.err.println("Captured: '" + matched + "'");
            contentBuffer.append(yytext());
            }
            // fall through
          case 26: break;
          case 7:
            { braceDepth++;
        contentBuffer.append(yytext());
            }
            // fall through
          case 27: break;
          case 8:
            { braceDepth--;
        if (braceDepth == 0) {
            // Found matching closing brace
            String content = contentBuffer.toString().trim();
            // System.out.println(content);
            yybegin(YYINITIAL);
            return symbol(sym.CONTENT, content);
        } else {
            contentBuffer.append(yytext());
        }
            }
            // fall through
          case 28: break;
          case 9:
            { return symbol(sym.AB);
            }
            // fall through
          case 29: break;
          case 10:
            { return symbol(sym.AU);
            }
            // fall through
          case 30: break;
          case 11:
            { return symbol(sym.BP);
            }
            // fall through
          case 31: break;
          case 12:
            { return symbol(sym.IP);
            }
            // fall through
          case 32: break;
          case 13:
            { return symbol(sym.NH);
            }
            // fall through
          case 33: break;
          case 14:
            { return symbol(sym.TL);
            }
            // fall through
          case 34: break;
          case 15:
            { return symbol(sym.AUI);
            }
            // fall through
          case 35: break;
          case 16:
            { return symbol(sym.BP_4);
            }
            // fall through
          case 36: break;
          case 17:
            { return symbol(sym.CB, yytext().substring(3));
            }
            // fall through
          case 37: break;
          case 18:
            { return symbol(sym.DATE);
            }
            // fall through
          case 38: break;
          case 19:
            { return symbol(sym.NH_1);
            }
            // fall through
          case 39: break;
          case 20:
            { return symbol(sym.NH_2);
            }
            // fall through
          case 40: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
