
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NH_2 = 9;
  public static final int IP = 12;
  public static final int NH_1 = 8;
  public static final int DATE = 6;
  public static final int AUI = 5;
  public static final int EOF = 0;
  public static final int TL = 2;
  public static final int AB = 11;
  public static final int P = 3;
  public static final int BP = 13;
  public static final int error = 1;
  public static final int AU = 4;
  public static final int NH = 7;
  public static final int CB = 15;
  public static final int BP_4 = 14;
  public static final int H = 10;
  public static final int CONTENT = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TL",
  "P",
  "AU",
  "AUI",
  "DATE",
  "NH",
  "NH_1",
  "NH_2",
  "H",
  "AB",
  "IP",
  "BP",
  "BP_4",
  "CB",
  "CONTENT"
  };
}

