\"This file was auto generated
.TL
Título

.AU
Autor

.AI
Instituição do Autor

.AB
Abstract content. Abstract content. Abstract content. Abstract content.  
Abstract content. Abstract content. Abstract content. Abstract content.  
Abstract content. Abstract content. Abstract content. Abstract content.  
Abstract content. Abstract content. Abstract content. Abstract content.

.AE
.NH
Header Numerado

.PP
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.

.NH
Header Numerado Explicito

.PP
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.

.NH 2
Header Numerado 2

.PP
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.
Isto é um parágrafo. Isto é um parágrafo. Isto é um parágrafo.

.SH
Header

.IP \(bu 2
Bullet Point

.IP \(bu 2
Bullet Point

.IP \(bu 2
Bullet Point

.IP \(bu 2
Bullet Point

.IP \(bu 2
Bullet Point

.IP \(bu 4
Bullet Point com 4 de identação
.IP \(bu 4
Bullet Point com 4 de identação
.IP \(bu 4
Bullet Point com 4 de identação
.IP \(bu 4
Bullet Point com 4 de identação
.IP \(bu 4
Bullet Point com 4 de identação
.SH
Python

.PP
Hello world em python.

.DS
.defcolor 076678 rgb #076678
.defcolor 32302f rgb #32302f
.defcolor 3c3836 rgb #3c3836
.defcolor 427b58 rgb #427b58
.defcolor 79740e rgb #79740e
.defcolor 7c6f64 rgb #7c6f64
.defcolor 8f3f71 rgb #8f3f71
.defcolor 928374 rgb #928374
.defcolor 9d0006 rgb #9d0006
.defcolor af3a03 rgb #af3a03
.defcolor b57614 rgb #b57614
.defcolor fbf1c7 rgb #fbf1c7
.nf
\f[CR]
\m[af3a03]print\m[](\m[79740e]"\m[]\m[79740e]Hello, World!\m[]\m[79740e]"\m[])

.fi
.DE
.SH
Rust

.PP
Hello world em rust.

.DS
.defcolor 076678 rgb #076678
.defcolor 32302f rgb #32302f
.defcolor 3c3836 rgb #3c3836
.defcolor 427b58 rgb #427b58
.defcolor 79740e rgb #79740e
.defcolor 7c6f64 rgb #7c6f64
.defcolor 8f3f71 rgb #8f3f71
.defcolor 928374 rgb #928374
.defcolor 9d0006 rgb #9d0006
.defcolor af3a03 rgb #af3a03
.defcolor b57614 rgb #b57614
.defcolor fbf1c7 rgb #fbf1c7
.nf
\f[CR]
\m[9d0006]fn\m[] \m[427b58]main\m[]() {
        \m[427b58]println!\m[](\m[79740e]"\m[]\m[79740e]Hello, World!\m[]\m[79740e]"\m[]);
    }

.fi
.DE

